# Generated by Django 3.1.2 on 2020-10-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0004_auto_20201026_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='imgdb/')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
