# Generated by Django 3.1.2 on 2020-10-26 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0005_auto_20201026_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(upload_to='..//Web//Testing//Demoapp//imgdb/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='..//Web//Testing//Demoapp//video/'),
        ),
    ]
