# Generated by Django 3.1.2 on 2020-10-29 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0007_auto_20201028_1137'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Login',
            new_name='AdminLogin',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
