# Generated by Django 3.1.2 on 2020-11-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0009_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ratings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(max_length=10)),
                ('movieId', models.CharField(max_length=7)),
                ('rating', models.CharField(max_length=6)),
                ('timestamp', models.CharField(max_length=10)),
            ],
        ),
    ]
