# Generated by Django 3.1.2 on 2020-11-01 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0010_ratings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ratings',
            new_name='Rating',
        ),
    ]
