# Generated by Django 3.1.2 on 2020-11-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0011_auto_20201101_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='average',
            field=models.CharField(default=5, max_length=5),
            preserve_default=False,
        ),
    ]
