# Generated by Django 3.1.2 on 2020-11-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0012_auto_20201101_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='average',
            field=models.CharField(max_length=6),
        ),
    ]
