# Generated by Django 3.1.2 on 2020-11-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0013_auto_20201101_2121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
