# Generated by Django 3.1.2 on 2020-11-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0014_delete_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=180)),
                ('genres', models.CharField(max_length=90)),
                ('imdbId', models.CharField(max_length=10)),
                ('average', models.CharField(max_length=6)),
            ],
        ),
    ]
