# Generated by Django 3.1.2 on 2020-11-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0015_movie'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
