# Generated by Django 3.1.2 on 2020-11-02 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0017_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.CharField(max_length=9)),
                ('title', models.CharField(max_length=180)),
                ('image', models.ImageField(upload_to='imgdb/')),
                ('video', models.FileField(upload_to='video/')),
            ],
        ),
    ]
