# Generated by Django 3.1.2 on 2020-11-02 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0018_movieimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieImg',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(null=True, upload_to='imgdb/'),
        ),
        migrations.AddField(
            model_name='movie',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
