# Generated by Django 3.1.2 on 2020-12-06 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demoapp', '0021_checkimg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckImg',
        ),
    ]
